export const Api = {
  TOKEN_TYPE: "bearer",
  BASE_URL: "http://ecotrippers.net/swept-app/api/",
  LOGIN: "login",
  SIGN_UP: "register",
  REGISTRATION: "register",
  FORGET_PASSWORD: "forget",
  VERIFY_CODE: "verify",
  RESET_PASSWORD: "reset",
  GET_PROFILE: "profile",
  UPDATE_PROFILE: "update/user",
  VERIFY_PROFILE: "verify",
  SERVICE_ENDPOINT: "service",
  ORDER_CLEANING: "order/cleaning",
  ORDER_PERSONAL_ITEM: "order/personalitem",
  ORDER_HANDIMEN: "order/handimen",
  ORDER_PETCARE: "order/petcare",
  GET_PER_CARE: "petcare",
  GET_CONCIERGE: "concierge",
  GET_HOMESPA: "homespa",
  POST_VERTUAL_ASS: "order/virtualasistant",
  POST_HOMESPA: "order/homespa",
  GET_ORDER_LIST_BY_ID: "user/orders",
  POST_CONCIERGE: "service/order/concierge",

  IMAGE_VIEW_BASE_URL: "https://ecotrippers.net/swept-app/storage/app/public/uploads/",
  BEAUTY_SPA_IMAGE: "BeautySpaImage/",
  HANDI_MEN_IMAGE: "HandymanServiceImage/",

};
