export const Api = {
  TOKEN_TYPE: "bearer",
  BASE_URL: "http://ecotrippers.net/swept-app/api/",
  LOGIN: "login",
  SIGN_UP: "register",
  REGISTRATION: "register",
  FORGET_PASSWORD: "forget",
  VERIFY_CODE: "verify",
  RESET_PASSWORD: "reset",
  GET_PROFILE: "profile",
  UPDATE_PROFILE: "update/user",
  VERIFY_PROFILE: "verify",
  SERVICE_ENDPOINT: "service",
  ORDER_CLEANING: "order/cleaning",
  ORDER_HANDIMEN: "order/handimen",
  ORDER_PETCARE: "order/petcare",
  GET_PER_CARE: "petcare",
  GET_CONCIERGE: "concierge",

};
